services:
  postgres:
    image: postgres:16-alpine
    container_name: fastify_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-fastify}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fastify_password}
      POSTGRES_DB: ${DB_NAME:-fastify_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-fastify}']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:16-alpine
    container_name: fastify_postgres_test
    environment:
      POSTGRES_USER: ${DB_USER:-fastify}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fastify_password}
      POSTGRES_DB: ${DB_NAME:-fastify_test_db}
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    profiles:
      - test

volumes:
  postgres_data:
  postgres_test_data:
